-- InvestFlow — table properties + RLS avec JWT Clerk (claim "sub" = user_id texte).
--
-- Prérequis côté Clerk :
--   JWT Templates → créer un template nommé exactement "supabase" (voir doc Clerk + Supabase).
--
-- Prérequis côté Supabase :
--   Authentication → Sign In / Up → Third-party auth → Clerk : renseigner l’issuer JWT Clerk.
--   Ainsi PostgREST reçoit le Bearer Clerk et auth.jwt()->>'sub' correspond à l’ID utilisateur Clerk.
--
-- Après modification : redéployer / recharger le schéma si besoin.

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  user_id text not null,
  name text,
  purchase_price numeric,
  renovation_cost numeric default 0,
  notary_fees numeric,
  total_project_cost numeric,
  monthly_rent numeric,
  tax_monthly numeric,
  charges_monthly numeric,
  vacancy_monthly numeric,
  monthly_cashflow numeric,
  net_yield numeric,
  credit_type text,
  city text,
  created_at timestamptz not null default now()
);

alter table public.properties add column if not exists credit_type text;
alter table public.properties add column if not exists city text;
alter table public.properties add column if not exists created_at timestamptz not null default now();

create index if not exists properties_user_id_idx on public.properties (user_id);

alter table public.properties enable row level security;

drop policy if exists "properties_select_own" on public.properties;
drop policy if exists "properties_insert_own" on public.properties;
drop policy if exists "properties_update_own" on public.properties;
drop policy if exists "properties_delete_own" on public.properties;

create policy "properties_select_own"
  on public.properties for select
  using ((auth.jwt()->>'sub') = user_id);

create policy "properties_insert_own"
  on public.properties for insert
  with check ((auth.jwt()->>'sub') = user_id);

create policy "properties_update_own"
  on public.properties for update
  using ((auth.jwt()->>'sub') = user_id)
  with check ((auth.jwt()->>'sub') = user_id);

create policy "properties_delete_own"
  on public.properties for delete
  using ((auth.jwt()->>'sub') = user_id);

grant all on table public.properties to postgres, service_role;
grant select, insert, update, delete on table public.properties to authenticated, anon;
