-- Transactions réelles par projet (suivi financier).

create table if not exists public.property_transactions (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties (id) on delete cascade,
  user_id text not null,
  occurred_on date not null,
  label text not null,
  amount numeric not null,
  category text,
  created_at timestamptz not null default now()
);

create index if not exists property_transactions_property_id_idx
  on public.property_transactions (property_id);

create index if not exists property_transactions_occurred_on_idx
  on public.property_transactions (property_id, occurred_on desc);

alter table public.property_transactions enable row level security;

drop policy if exists "property_transactions_select_own" on public.property_transactions;
drop policy if exists "property_transactions_insert_own" on public.property_transactions;
drop policy if exists "property_transactions_update_own" on public.property_transactions;
drop policy if exists "property_transactions_delete_own" on public.property_transactions;

create policy "property_transactions_select_own"
  on public.property_transactions for select
  using ((auth.jwt()->>'sub') = user_id);

create policy "property_transactions_insert_own"
  on public.property_transactions for insert
  with check (
    (auth.jwt()->>'sub') = user_id
    and exists (
      select 1 from public.properties p
      where p.id = property_id and p.user_id = (auth.jwt()->>'sub')
    )
  );

create policy "property_transactions_update_own"
  on public.property_transactions for update
  using ((auth.jwt()->>'sub') = user_id)
  with check ((auth.jwt()->>'sub') = user_id);

create policy "property_transactions_delete_own"
  on public.property_transactions for delete
  using ((auth.jwt()->>'sub') = user_id);

grant all on table public.property_transactions to postgres, service_role;
grant select, insert, update, delete on table public.property_transactions to authenticated, anon;
