-- InvestFlow — cache des résultats Discover (Apify) par ville.

create table if not exists public.listings_cache (
  id bigint generated by default as identity primary key,
  city text not null unique,
  data jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists listings_cache_city_idx on public.listings_cache (city);

alter table public.listings_cache enable row level security;

drop policy if exists "listings_cache_select_all" on public.listings_cache;
create policy "listings_cache_select_all"
  on public.listings_cache for select
  using (true);

-- Écriture : on évite d’ouvrir l’insert/update en public.
-- Le service role (utilisé côté serveur) contourne RLS.
revoke insert, update, delete on table public.listings_cache from anon, authenticated;

grant select on table public.listings_cache to anon, authenticated;
grant all on table public.listings_cache to service_role;

